package models;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * Represents an electronic product available in the store.
 * Corresponds to a row in the Products database table.
 */
public class Product {
    private String productId;       // Primary key (e.g., PROD_XYZ)
    private String name;            // Product name (e.g., "Laptop XYZ")
    private String brand;           // Manufacturer brand (e.g., "Dell", "Apple")
    private String model;           // Specific model number/name (e.g., "XPS 15 9530")
    private String description;     // Detailed description of the product
    private double price;           // Current selling price
    private int stock;              // Current quantity available in inventory
    private LocalDate manufactureDate; // Date of manufacture (optional)
    private String imageUrl;        // URL or path to the product's image (optional)
    private String categoryId;      // Foreign key linking to the Categories table (optional)

    // Formatter for dates in toString() or other display methods
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    /**
     * Constructs a Product object.
     * Product ID can be null initially if it's intended to be generated by a manager.
     *
     * @param productId       The unique ID for the product (can be null initially).
     * @param name            The name of the product (required).
     * @param brand           The manufacturer brand (optional).
     * @param model           The specific model (optional).
     * @param description     A description of the product (optional).
     * @param price           The selling price (must be non-negative).
     * @param stock           The available stock quantity (must be non-negative).
     * @param manufactureDate The date of manufacture (optional, can be null).
     * @param categoryId      The ID of the category this product belongs to (optional).
     * @param imageUrl        The URL or path to the product image (optional).
     */
    public Product(String productId, String name, String brand, String model, String description,
                   double price, int stock, LocalDate manufactureDate, String categoryId, String imageUrl) {

        // --- Validation for other fields ---
        if (name == null || name.trim().isEmpty())
            throw new IllegalArgumentException("Product name cannot be null or empty.");
        if (price < 0)
            throw new IllegalArgumentException("Product price cannot be negative.");
        if (stock < 0)
            throw new IllegalArgumentException("Product stock cannot be negative.");

        // Assign values
        this.productId = productId; // productId can be null here, will be set by manager before DB persistence
        this.name = name;
        this.brand = brand;
        this.model = model;
        this.description = description;
        this.price = price;
        this.stock = stock;
        this.manufactureDate = manufactureDate;
        this.imageUrl = imageUrl;
        this.categoryId = categoryId;
    }

    // --- Getters ---
    public String getProductId() { return productId; }
    public String getName() { return name; }
    public String getBrand() { return brand; }
    public String getModel() { return model; }
    public String getDescription() { return description; }
    public double getPrice() { return price; }
    public int getStock() { return stock; }
    public LocalDate getManufactureDate() { return manufactureDate; }
    public String getImageUrl() { return imageUrl; }
    public String getCategoryId() { return categoryId; }

    // --- Setters (Allow modification of product details) ---
    public void setProductId(String productId) {
         // This setter will be called by the ProductManager after ID generation.
         // It should now receive a valid, non-null, non-empty ID.
         if (productId == null || productId.trim().isEmpty())
             throw new IllegalArgumentException("Product ID cannot be set to null or empty.");
        this.productId = productId;
    }
    public void setName(String name) {
        if (name == null || name.trim().isEmpty())
             throw new IllegalArgumentException("Product name cannot be set to null or empty.");
        this.name = name;
    }
    public void setBrand(String brand) { this.brand = brand; }
    public void setModel(String model) { this.model = model; }
    public void setDescription(String description) { this.description = description; }
    public void setPrice(double price) {
        if (price < 0) throw new IllegalArgumentException("Product price cannot be negative.");
        this.price = price;
    }
    public void setStock(int stock) {
        if (stock < 0) throw new IllegalArgumentException("Product stock cannot be negative.");
        this.stock = stock;
    }
    public void setManufactureDate(LocalDate manufactureDate) { this.manufactureDate = manufactureDate; }
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }
    public void setCategoryId(String categoryId) { this.categoryId = categoryId; }


    // --- Overrides ---
    @Override
    public String toString() {
        return "Product{" +
               "id='" + (productId != null ? productId : "NOT_YET_SET") + '\'' + // Handle potentially null ID
               ", name='" + name + '\'' +
               ", brand='" + (brand != null ? brand : "N/A") + '\'' +
               ", model='" + (model != null ? model : "N/A") + '\'' +
               ", price=₹" + String.format("%.2f", price) +
               ", stock=" + stock +
               ", mfgDate=" + (manufactureDate != null ? manufactureDate.format(DATE_FORMATTER) : "N/A") +
               ", catId='" + (categoryId != null ? categoryId : "N/A") + '\'' +
               '}';
    }

    /**
     * Checks for equality based primarily on the productId.
     * If productId is null for either object, falls back to reference equality
     * or requires other fields to match if that's desired for transient objects.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        // If IDs are set, they must match.
        // If one ID is null and the other isn't, they are not equal.
        // If both IDs are null, then consider other fields or reference equality (super.equals(o))
        if (productId != null) {
            return Objects.equals(productId, product.productId);
        } else {
            // If this.productId is null, they are only equal if product.productId is also null
            // AND other identifying fields match (or by reference if it's the same unsaved object)
            // For simplicity here, if ID is null, we only consider them equal if they are the same instance
            // or if the other object also has a null ID and other critical fields match.
            // A robust equals for unsaved entities can be complex.
            return product.productId == null && Objects.equals(name, product.name) && Objects.equals(brand, product.brand) && Objects.equals(model, product.model);
        }
    }

    /**
     * Generates a hash code. If productId is set, it's used.
     * Otherwise, a hash based on other core fields or super.hashCode() is used.
     */
    @Override
    public int hashCode() {
        if (productId != null) {
            return Objects.hash(productId);
        }
        // Hash based on other fields if ID is not yet set
        return Objects.hash(name, brand, model, price, stock);
    }
}